### ISSUE TITLE
Add multiplayer chat functionality

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#100]
https://www.notion.so/webaverse-app-eb803ec9495c4a31b5806f10294ce011

**Comment by anu-nexus** [comment]
This issue has resolved. Chat functionality has been added. kindly watch screenshot.

![Screenshot (222)](https://user-images.githubusercontent.com/101788714/173809093-90c0e550-7b59-4e3b-99a5-81f619d69bde.png)
