### ISSUE TITLE
Fix stuttering / jaggedy avatar interpolation

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#2]

**Comment by anu-nexus** [comment]
Above problem has resolved but now When player wear a pet , movement of pet is stuttering at remote location.
https://www.awesomescreenshot.com/video/8728263?key=b3e94fd195ee280344ad7fe5299d769b

**Comment by anu-nexus** [comment]
Now pet is not stuttering but remote player is stuttering.
https://www.awesomescreenshot.com/video/8749954?key=2a9f6a78a8cc16b0bfec3de68447ded6

**Comment by anu-nexus** [comment]
player is stuttering
https://www.awesomescreenshot.com/video/8844775?key=8b3afc62ab6dfaebb00e6b0052e6a4d3

**Comment by anu-nexus** [comment]
Player is stuttering at remote location. Kindly watch video for reference:

https://user-images.githubusercontent.com/101788714/170688656-91e2a2db-1480-4874-bee4-2cacd0c4358a.mp4
