### ISSUE TITLE
Issues with single player joining multiplayer

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#22]
https://www.notion.so/webaverse-app-4b1f76bd97c44295b2361f4eac447066

**Comment by saddamjit** [comment]
@anu-nexus needs to setup the project in her local machine and replicate this issue. She is welcomed to add more details in form of images and video so that Kinjal should understand it in more detail

**Comment by alisaad673** [comment]
-So right now, Once we equip items in single player and shift to multiplayer room. The items do get replicated but not attached to the avatar. 
-As it can be seen in the video below, When we shift from single player to multiplayer room along with items such as sword, helmet.. These items do appear in remote instance of multiplayer room, but not attached to the avatar. 
-I wasn't able to reproduce other issues stated above such as avatar disappearing right now. Maybe the dev can add more details on how to reproduce these.

https://user-images.githubusercontent.com/35926530/163600113-5a6d00f3-7ab5-479e-82f2-a1dc0ef7b4b1.mp4

Meanwhile, You may also check these issues pointed out by me here:
https://github.com/webaverse/app/pull/2807#issuecomment-1095384244

**Comment by lalalune** [comment]
This is still happening

**Comment by lalalune** [comment]
https://user-images.githubusercontent.com/18633264/164958686-5f2cd0a3-7377-4f6f-ac0d-99eb861c14b7.png

**Comment by anu-nexus** [comment]
When single player joins multiplayer, grabble item is worn by player but its not working.
Kindly watch the video.
https://www.awesomescreenshot.com/video/8697925?key=f7240e8710894cd41407e6af2610f219

**Comment by kinjalravel** [comment]
@anu-nexus have you taken latest pull from master?

**Comment by anu-nexus** [comment]
![Screenshot (186)](https://user-images.githubusercontent.com/101788714/166666007-b5a98662-608d-4ab3-80de-ece4272778d7.png)
When a player joins multiplayer, grabbed sword is showing but animation is not working.  
If player wear helmet  and joins multiplayer then it is showing bug. 
https://www.awesomescreenshot.com/video/8697925?key=f7240e8710894cd41407e6af2610f219

**Comment by anu-nexus** [comment]
When single player joins multiplayer, player is joining multiplayer with sword and animation is also available but after releasing sword that local player is not able to wear that sword again.
https://www.awesomescreenshot.com/video/8844469?key=0f2e5eaacb8977bc695f9afc408a4f67

**Comment by anu-nexus** [comment]
Once we equip items in single player and shift to multiplayer room. The items do get replicated but not attached to the avatar.

-As it can be seen in the video below, When we shift from single player to multiplayer room along with items such as sword, helmet.. These items do appear in remote instance of multiplayer room, but not attached to the avatar.

https://www.awesomescreenshot.com/video/9042974?key=9d043d6a10d7bdac3f778df7a891da7a

**Comment by anu-nexus** [comment]
This issue has been resolved.
https://user-images.githubusercontent.com/101788714/170948098-9b22c04e-03c6-493b-83e6-82a212e30236.mp4
