### ISSUE TITLE
Pet should look at current owner (if owner is remote player)

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#35]
Right now, pet looks at local player no matter what. Also, when remote player releases the pet, the pet starts following the local player.

![image](https://user-images.githubusercontent.com/18633264/164951238-e8946128-d88b-4dd4-a49c-6651d3fdce5b.png)

**Comment by anu-nexus** [comment]
- Pet is watching at only local player but it is not replicated in other window. If in one window, pet is watching at local player but in remote player pet is not moving.
https://www.awesomescreenshot.com/video/8695241?key=621fb971ce89e9d0ae583f063241afd1

There are several issues are available like: 
- If we are carrying/releasing pet for more than 2-3 times, it is going hanged.
- And after releasing pet, pet is still moving behind the player.
Kindly visit this link .
 https://www.awesomescreenshot.com/video/8695329?key=8651ebe9ed3c84dea7d0eb37d7ef1ff4

**Comment by anu-nexus** [comment]
Above problem has resolved but now When player wear a pet , movement of pet is stuttering at remote location.
https://www.awesomescreenshot.com/video/8728263?key=b3e94fd195ee280344ad7fe5299d769b
