### ISSUE TITLE
Move wear/unwear code from player observer function to individual tracked app observe function

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#37]
![image](https://user-images.githubusercontent.com/18633264/164955608-7428b07a-551a-4d40-814c-2a1bb19b7c6d.png)

**Comment by sayhellometaverse2022** [comment]
This issue seems to closed, please open this again if we still have this one.

**Comment by DavinciDreams** [comment]
https://github.com/webaverse/app/issues/469
