### ISSUE TITLE
QA Multiplayer

### ISSUE THREAD

**Issue by kinjalravel** [TheNexusCity/webaverse-app#41]
We want to verify that multiplayer functionality is working, specifically:

Player joins and leaves scenes without causing unwanted bugs or problems, including duplicated items or avatars or missing animation or state
Player joins a world with a wearable from another world and brings their wearables along with them
Player wears and unwears weapons on local and remote player
Player mounts and unmounts vehicles on local and multiplayer
Player animation state works when running, flying and fast-running (sonic boom / naruto run)

**Comment by lalalune** [comment]
@anu-nexus this relies on #22 and #48 being finished to complete
