### ISSUE TITLE
Mic causing feedback into self on local player

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#51]
https://github.com/webaverse/wsrtc/commit/38fc7d7b264de561e61592081bde61039d54f6ce

Anu said the app waas recording when it shouldn't, try uncommenting line 339

**Comment by anu-nexus** [comment]
Mic on/off button is not working. Mic can save voice even it is off.
https://www.awesomescreenshot.com/video/8845460?key=88dfaa890078a37fbe65d5c3ed358a5a

**Comment by anu-nexus** [comment]
Mic on/off button is not working correctly. 
https://www.awesomescreenshot.com/video/9042667?key=e60dd101acdb8d773ebf4e2dc7b17a2a

**Comment by anu-nexus** [comment]
Mike is on but voice is not recording. Kindly watch video for 

https://user-images.githubusercontent.com/101788714/171147018-f72d023c-3877-44c7-a88f-b048e253ecec.mp4

reference.
