### ISSUE TITLE
Fix Gun

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#60]
![image](https://user-images.githubusercontent.com/18633264/167626027-c3fe5b06-9f75-460c-a279-63bbc161ccd6.png)

**Comment by alisaad673** [comment]
Same is the issue with wearing Machine Gun/Bow/Pistol

![Equipping machine gun crashes the app](https://user-images.githubusercontent.com/35926530/167916633-615c8cd0-2c19-4a05-85c3-3a445988e3ba.PNG)
![euipping bow gives error](https://user-images.githubusercontent.com/35926530/167916645-268f5a62-9f35-46a8-81d3-a1d386bbac2e.PNG)

**Comment by anu-nexus** [comment]
Kindly watch this video. It will show working of gun.
https://www.awesomescreenshot.com/video/9047480?key=75958a51f49c0c180eaff6a34044dd57
