### ISSUE TITLE
Scene Switching/Gettitng out of multiplayer isn't working 

### ISSUE THREAD

**Issue by alisaad673** [TheNexusCity/webaverse-app#64]
Right now we are unable to switch scenes in multiplayer as it gets us out of multiplayer. And the scene doesn't loads
Same is the case with getting out of multiplayer too(By clicking wifi button)

![image](https://user-images.githubusercontent.com/35926530/167919584-0079b3b6-9728-4ece-8b94-28d7f9c1cf18.png)

https://user-images.githubusercontent.com/35926530/167919810-5b7bc867-efb4-4ef7-b0e1-e94b7a97923a.mp4

**Comment by anu-nexus** [comment]
Scene changing issue has resolved. kindly watch video for reference.


https://user-images.githubusercontent.com/101788714/171169230-fa41ab49-fb73-4218-987f-ce1bb28d4b4f.mp4
