### ISSUE TITLE
Character Select in Character tab is bugged

### ISSUE THREAD

**Issue by alisaad673** [TheNexusCity/webaverse-app#65]
Firstly, There is not left character panel showing here.(Its there in master). Maybe It needs to be rebased into latest master.
![image](https://user-images.githubusercontent.com/35926530/167925342-e274259f-f566-4d14-a4b3-0f7689410c5d.png)

While we parse over characters in Character tab, It gives this error and we are unable to select avatars/

![image](https://user-images.githubusercontent.com/35926530/167921959-12e3efec-8d8b-4871-b1c5-bfcd7d0d3faa.png)

https://user-images.githubusercontent.com/35926530/167922006-203e2de2-c6f6-421f-84be-f51bd06fc3b7.mp4

**Comment by Emmyn5600** [comment]
https://user-images.githubusercontent.com/55635977/169311113-e92b5486-b807-4d46-9ca8-dde8e091c0a5.mp4

**Comment by Emmyn5600** [comment]
https://user-images.githubusercontent.com/55635977/169312209-147db02a-0323-4504-9727-66a46f07a5ce.mp4
