### ISSUE TITLE
Player is not damaging remote player

### ISSUE THREAD

**Issue by alisaad673** [TheNexusCity/webaverse-app#66]
Right now, We are unable to do combat with other player as there is no effect of Weapon on them. 

https://user-images.githubusercontent.com/35926530/167923065-80a5cfe9-f155-4a09-bfd8-d9746c25dd9e.mp4

**Comment by anu-nexus** [comment]
This issue has been resolved. Kindly watch video for reference.


https://user-images.githubusercontent.com/101788714/171170709-4142445b-726e-443c-9f76-958a96935c00.mp4
