### ISSUE TITLE
Fruit Eating is bugged

### ISSUE THREAD

**Issue by alisaad673** [TheNexusCity/webaverse-app#68]
Right now if we equip fruit in one instance and finish eating it, It ends in its own instance but there appears an instance of fruit out of nowhere in the other player's instance.

https://user-images.githubusercontent.com/35926530/167925968-5194d169-64a6-444a-bbce-5809e3acec34.mp4

**Comment by lalalune** [comment]
When player A picks up the fruit, it appears in their hand
When they eat it, it disappears on their screen, but appears at position 0 on Player B
Player B can pick it up and eat it it, but it will play back on Player A

**Comment by lalalune** [comment]
Looks like there is a bad local player reference, where we want to get the acting player instead. I picked this up on Player B and it went into player A's hand

![image](https://user-images.githubusercontent.com/18633264/167973446-be7d07d4-6b53-4e76-a070-052dd602d531.png)

**Comment by metadev26** [comment]
Looks like this is a network timing / ordering issue.
I've checked if the player reference is correct and it receives the correct player reference for local and remote player.
For now the issue only happens for remote player's screen.
![unknown](https://user-images.githubusercontent.com/99482765/169708761-12dac18c-c481-4d42-bbba-d5e4267ebacd.png)
So in my opinion, the reason why this issue happens is `trackedappimport` and `trackedappexport` called different between local and remote player.
As you can see in the screenshot, for the local player, the `trackedappimport` and `trackedappexport` called before `unwear` called.
But on the remote player side, they called after `unwear` function called.
