### ISSUE TITLE
Gun aim animation not playing on remote player

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#73]

**Comment by DavinciDreams** [comment]
menuAim() {
    const localPlayer = metaversefileApi.useLocalPlayer();
    if (!localPlayer.hasAction('aim')) {
      const localPlayer = metaversefileApi.useLocalPlayer();
      const wearApp = loadoutManager.getSelectedApp();
      const wearAimApp = (() => {
        if (wearApp) {
          const aimComponent = wearApp.getComponent('aim');
          if (aimComponent) {
            return wearApp;
          }
        }
        return null;
      })();
      const wearAimComponent = wearAimApp?.getComponent('aim');

      const {instanceId} = wearAimApp ?? {};
      const {appAnimation, playerAnimation, boneAttachment, position, quaternion, scale} = wearAimComponent ?? {};
      const aimAction = {
        type: 'aim',
        instanceId,
        appAnimation,
        playerAnimation,
        boneAttachment,
        position,
        quaternion,
        scale,
      };
      localPlayer.addAction(aimAction);
    }
  }
  menuUnaim() {
    const localPlayer = metaversefileApi.useLocalPlayer();
    const aimAction = localPlayer.getAction('aim');
    if (aimAction) {
      localPlayer.removeAction('aim');
    }
    
 https://github.com/webaverse/app/blob/7adb0fca8968bc42f1943c6ce98d4add8a8b0fb6/game.js
