### ISSUE TITLE
Intermittent crash when wearing / unwearing -- cannot bind impl key to path

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#83]
Under certain circumstances our app is failing to bind and something is going wrong -- we're trying to get a new tracked app or something?

To reproduce -- join world with two players and wear/unear weapon repeatedly

**Comment by alextitonis** [comment]
Got this error when tried to reproduce it
![Screenshot_41](https://user-images.githubusercontent.com/45359358/169646217-f118005c-89f2-4647-abea-c2794e80bf2f.png)

**Comment by alextitonis** [comment]
After adding some checks to avoid looping the appsArray if not an iterable, got this error (both errors crashed the server
![Screenshot_42](https://user-images.githubusercontent.com/45359358/169646537-56280348-ae2c-40bb-88f9-db408905c135.png)
)
