### ISSUE TITLE
Multiplayer: Items duplicating on re-wear 

### ISSUE THREAD

**Issue by DavinciDreams** [TheNexusCity/webaverse-app#86]
https://github.com/webaverse/app/issues/2701

**Comment by sayhellometaverse2022** [comment]
To make sure this error, I tried to these tests.
Let's assume User A is host player. User B and User C are remote players
- [ ] User A create remote room. User B into the remote room. User A grab sword
- [ ] User A create remote room. User B grab the sword, User B into the remote room
- [ ] User A grab sword on local. User A create remote room,  User B into the remote room

I am going to test/fix the issue from these steps.

**Comment by anu-nexus** [comment]
[ ] User A create remote room. User B into the remote room. User A wear a sword and enter into local room. Now User A release sword. Try to wear released sword again.

**Comment by anu-nexus** [comment]
[ ] User A in local room. When player wear a sword, player face and hand movement should be towards sword. Check the face and hand movement of player by changing player position.

**Comment by sayhellometaverse2022** [comment]
- [ ]  when single player join multiplayer with sword, sword is visible but animation is missing.
- [ ] wearing sword can be wear by other player without performing unwearing
- [ ] on single player, wearing/unwearing sound is fine but on mutiplayer wearing/unwearing sound is double.
Thanks
